# ./.tmuxinator.yml

name: argon
root: .

windows:
    - Nvim:
          - clear
          - nvim .
    - Server Run:
          - clear
    - Server:
          - clear
    - Git:
          - clear
          - gs
