# ./.tmuxinator.yml

name: argon
root: .

windows:
    - Nvim:
          - clear
          - nvim .
    - Desktop client:
          - cd desktop/src-tauri/
          - clear
    - Desktop client backend:
          - cd desktop/src-tauri/
          - clear
    - Git:
          - clear
          - gs
