# ./.tmuxinator.yml

name: argon
root: .

windows:
    - nvim:
          - clear
          - nvim .
    - run:
          - clear
    - tauri backend:
          - cd src-tauri/
          - clear
    - git:
          - clear
          - gs
